name: Django CI

on:
  push:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests and Generate Coverage Report
        run: |
          coverage run --source='.' manage.py test tasks
          coverage xml
      - name: 'Upload coverage to Codecov'
        uses: codecov/codecov-action@v2
